# Generated by Django 5.2.5 on 2025-08-07 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Generation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret_key', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('before_url', models.URLField(null=True)),
                ('after_url', models.URLField(null=True)),
                ('status', models.CharField(default='created', max_length=20)),
            ],
        ),
    ]
